env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: "off"
  no-underscore-dangle: "off"
  import/no-extraneous-dependencies: "off"
  import/order:
    - error
    - pathGroups:
        - pattern: "@**/**"
          group: parent
      groups:
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: always
  import/prefer-default-export: "off"
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
  react/jsx-props-no-spreading: "off"
  "react/prop-types": "off"
  react/require-default-props: "off"
  react/static-property-placement:
    - error
    - static public field
  no-use-before-define: "off"
  no-unused-vars: "error"
  no-useless-constructor: "off"
  no-shadow: "off"
  react/react-in-jsx-scope: "off"
  import/no-cycle: "off"
  react/destructuring-assignment: "off"
  no-plusplus: "off"
  camelcase: "off"
  quotes:
    - error
    - single
    - backstick
  semi:
    - error
    - always
  indent: "off"
  no-multi-spaces:
    - error
  import/no-named-as-default: "off"
  react/no-unused-prop-types: "off"
  react/function-component-definition: "off"
  no-multi-assign: "off"
  jsx-a11y/aria-role: "off"
  jsx-a11y/no-static-element-interactions: "off"
  jsx-a11y/click-events-have-key-events: "off"
  no-lonely-if: "off"
  no-nested-ternary: "off"
  no-param-reassign: "off"
  space-before-function-paren: "off"
  react/no-unknown-property: "off"
